import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/navigation/footer'
import Navbar from '@/components/navigation/navbar'
import { RoutesType } from '@/lib/main.types'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const routes : RoutesType[] =  [
  {
    href: '/',
    label: 'Home',
    targetSegment: null,
    description: 'Initial page',
  }
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar routesArr={routes} title='BeeOnDWeb Gallery'  />        
        {children}
        <Footer />
        </body>
    </html>
  )
}
